require "thor"
require "octokit"
require "faraday"
require "faraday/retry"
require "concurrent"
require "sqlite3"
require "tty/prompt"
require "tty/table"
require "tty/spinner"
require "pastel"
require "dotenv"
require "psych"
require "json"
require "fileutils"
require "time"


module Reviewbot
  module CLI; end
  module GitHub; end
  module Git; end
  module AI; end
  module Pipelines; end
  module Reviewers; end
  module Analyzers; end
  module Services
    module Detectors; end
  end
  module Formatters
    module Markdown; end
    module Terminal; end
  end
  module Cache; end
  module Models; end
  module Config; end
  module Utils; end
end

require_relative "reviewbot/version"
require_relative "reviewbot/utils/logger"
require_relative "reviewbot/utils/error_handler"
require_relative "reviewbot/config/defaults"
require_relative "reviewbot/config/loader"
require_relative "reviewbot/config/validator"
require_relative "reviewbot/config/options"
require_relative "reviewbot/config/repository_config"
require_relative "reviewbot/models/repository"
require_relative "reviewbot/models/pull_request"
require_relative "reviewbot/models/review_run"
require_relative "reviewbot/models/finding"
require_relative "reviewbot/models/repo_profile"
require_relative "reviewbot/models/diff_file"
require_relative "reviewbot/models/diff_chunk"
require_relative "reviewbot/models/analysis_result"
require_relative "reviewbot/cache/database"
require_relative "reviewbot/cache/repository"
require_relative "reviewbot/cache/pull_request"
require_relative "reviewbot/cache/review_run"
require_relative "reviewbot/cache/finding"
require_relative "reviewbot/cache/diff_cache"
require_relative "reviewbot/cache/manager"
require_relative "reviewbot/github/client"
require_relative "reviewbot/github/pr_fetcher"
require_relative "reviewbot/github/pr_lister"
require_relative "reviewbot/github/comment_publisher"
require_relative "reviewbot/github/rate_limiter"
require_relative "reviewbot/github/diff_fetcher"
require_relative "reviewbot/git/cli"
require_relative "reviewbot/git/pr_checker"
require_relative "reviewbot/git/branch_manager"
require_relative "reviewbot/git/repo_manager"
require_relative "reviewbot/services/pr_selector"
require_relative "reviewbot/services/pr_manager"
require_relative "reviewbot/services/repo_detector"
require_relative "reviewbot/services/detectors/ruby_detector"
require_relative "reviewbot/services/detectors/rails_detector"
require_relative "reviewbot/services/detectors/node_detector"
require_relative "reviewbot/services/detectors/flutter_detector"
require_relative "reviewbot/services/detectors/dart_detector"
require_relative "reviewbot/services/detectors/go_detector"
require_relative "reviewbot/services/diff_extractor"
require_relative "reviewbot/services/file_categorizer"
require_relative "reviewbot/services/diff_chunker"
require_relative "reviewbot/services/diff_filter"
require_relative "reviewbot/services/review_context"
require_relative "reviewbot/services/review_coordinator"
require_relative "reviewbot/services/pipeline_orchestrator"
require_relative "reviewbot/services/report_exporter"
require_relative "reviewbot/analyzers/runner"
require_relative "reviewbot/analyzers/rubocop_runner"
require_relative "reviewbot/analyzers/brakeman_runner"
require_relative "reviewbot/analyzers/reek_runner"
require_relative "reviewbot/analyzers/eslint_runner"
require_relative "reviewbot/analyzers/typescript_runner"
require_relative "reviewbot/analyzers/dart_analyzer_runner"
require_relative "reviewbot/analyzers/golangci_lint_runner"
require_relative "reviewbot/analyzers/go_vet_runner"
require_relative "reviewbot/analyzers/orchestrator"
require_relative "reviewbot/ai/client"
require_relative "reviewbot/ai/retry_handler"
require_relative "reviewbot/ai/token_budget"
require_relative "reviewbot/ai/prompt_builder"
require_relative "reviewbot/ai/response_parser"
require_relative "reviewbot/ai/review_cache"
require_relative "reviewbot/ai/review_engine"
require_relative "reviewbot/ai/incremental_reviewer"
require_relative "reviewbot/reviewers/base"
require_relative "reviewbot/reviewers/ruby_reviewer"
require_relative "reviewbot/reviewers/rails_reviewer"
require_relative "reviewbot/reviewers/javascript_reviewer"
require_relative "reviewbot/reviewers/typescript_reviewer"
require_relative "reviewbot/reviewers/react_reviewer"
require_relative "reviewbot/reviewers/flutter_reviewer"
require_relative "reviewbot/reviewers/dart_reviewer"
require_relative "reviewbot/reviewers/go_reviewer"
require_relative "reviewbot/reviewers/reviewer_factory"
require_relative "reviewbot/pipelines/base"
require_relative "reviewbot/pipelines/ruby_pipeline"
require_relative "reviewbot/pipelines/node_pipeline"
require_relative "reviewbot/pipelines/flutter_pipeline"
require_relative "reviewbot/pipelines/go_pipeline"
require_relative "reviewbot/formatters/markdown/report"
require_relative "reviewbot/formatters/markdown/summary_section"
require_relative "reviewbot/formatters/markdown/findings_section"
require_relative "reviewbot/formatters/markdown/file_breakdown_section"
require_relative "reviewbot/formatters/markdown/missing_tests_section"
require_relative "reviewbot/formatters/markdown/architecture_notes_section"
require_relative "reviewbot/formatters/markdown/security_notes_section"
require_relative "reviewbot/formatters/terminal/display"
require_relative "reviewbot/formatters/terminal/pr_table"
require_relative "reviewbot/formatters/terminal/findings_summary"
require_relative "reviewbot/cli/base"
require_relative "reviewbot/cli/prs"
require_relative "reviewbot/cli/review"
require_relative "reviewbot/cli/publish"
require_relative "reviewbot/cli/export"
require_relative "reviewbot/cli/cache"
