module Reviewbot
  module GitHub
    class CommentPublisher
      def initialize(client: nil)
        @client = client || Client.new
      end

      def publish(repo_full_name:, pr_number:, summary:, findings:, commit_id: nil, event: "COMMENT")
        comments = build_comments(findings)
        body = build_summary_body(summary)

        opts = { body: body, comments: comments, event: event }
        opts[:commit_id] = commit_id if commit_id

        @client.create_pull_request_review(
          repo_full_name,
          pr_number,
          **opts
        )
      end

      private

      def build_comments(findings)
        findings.select { |f| f[:file_path] && f[:line_number] }
          .map { |f| format_comment(f) }
      end

      def format_comment(finding)
        {
          path: finding[:file_path],
          line: finding[:line_number],
          body: format_finding_body(finding)
        }
      end

      def format_finding_body(finding)
        severity_icon = case finding[:severity]
                        when "critical" then "🔴 CRITICAL"
                        when "high" then "⚠️ HIGH"
                        when "medium" then "🔶 MEDIUM"
                        else "ℹ️ LOW"
                        end

        body = "**#{severity_icon}: #{finding[:title]}**\n\n"
        body += "#{finding[:description]}\n" if finding[:description]
        body += "\n**Suggestion:** #{finding[:suggestion]}" if finding[:suggestion]
        body
      end

      def build_summary_body(summary)
        body = "## Reviewbot Review Summary\n\n"
        body += "#{summary[:text]}\n\n" if summary[:text]

        if summary[:finding_counts]
          body += "### Findings Summary\n\n"
          body += "| Severity | Count |\n"
          body += "|----------|-------|\n"
          %w[critical high medium low].each do |sev|
            count = summary[:finding_counts][sev] || 0
            body += "| #{sev.capitalize} | #{count} |\n" if count > 0
          end
          body += "\n"
        end

        body += "_This review was generated by reviewbot_"
        body
      end
    end
  end
end
